Expression -> AddSubOperation

AddSubOperation  -> MultDivOperation AddSubOperationP
AddSubOperationP -> addSub MultDivOperation AddSubOperationP
                 |  EPSILON

MultDivOperation  -> PrimaryOperation:primary MultDivOperationP
MultDivOperationP -> multDiv PrimaryOperation MultDivOperationP
                  |  EPSILON

PrimaryOperation -> startDel Expression endDel
                 |  intLiteral