c = Class
P = Procedure
V = Variable
O = Object
D = Dec
s = Simple#S
S = Stm
s_C = #c#S
s_if = IfChains
n = Num      
v = Val
lv = LVal
x = #VNames
o = #ONames
C = #cNames
p = #PNames
T = Types      
e = Exp
b = Bool#e
i = Int#e
D_C = #D#c
D_P = #D#P
D_V = #D#V
D_O = #D#O