Program -> Statement 
        | EPSILON

Statement	->  CompoundStatement
		| ScopedLevelStatement
		| ProcedureDeclaration
        
CompoundStatement -> Statement Newline SStatement

ScopedLevelStatement ->  Newline 
		| Expression
		| CompoundScopedLevelStatement
		| IdentifierDcl
        | IdentifierDclAssign 
		| Assignment
		| ReturnExpression
		| IfStatement
        | IfElseIfStatement
        | IfElseStatement
		| WhileStatement

Newline -> nl

IdentifierDcl -> T VariableNames

IdentifierDclAssign -> T VariableNames = Expression 

WhileStatement -> while ( BooleanExpression ) indent ScopedLevelStatement dedent

Assignment -> LeftValue = Expression 

CompoundScopedLevelStatement -> ScopedLevelStatement Newline ScopedLevelStatement

IfStatement -> if ( BooleanExpression ) indent ScopedLevelStatement dedent 

IfElseIfStatement -> if ( BooleanExpression ) indent ScopedLevelStatement dedent else IfStatement                     

IfElseStatement -> if ( BooleanExpression ) indent ScopedLevelStatement dedent else indent ScopedLevelStatement dedent
                                           
Expression	->  VariableNames 
		| IntegerExpression 
		| BooleanExpression 
		| ParenthesisExpression 
		| ProcedecureCall
        | RegisterExpression

RegisterExpression -> register ( IntegerExpression )

ProcedecureCall -> ProcedureName ( Expression , Expression_1 , ... , Expression_k )
        
ParenthesisExpression -> ( Expression )        

ReturnExpression -> return Expression

IntegerExpression	-> Numerals   
		| expression 
		| AddOp
		| SubOp
		| MulOp
		| DivOp 
		| ModOp 
		| PowOp

AddOp -> IntegerExpression + IntegerExpression

SubOp -> IntegerExpression - IntegerExpression

MulOp -> IntegerExpression * IntegerExpression

DivOp -> IntegerExpression / IntegerExpression

ModOp -> IntegerExpression % IntegerExpression

PowOp -> IntegerExpression ^ IntegerExpression
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
BooleanExpression	->  true 
		| false 
		| Expression 
		| EqOp 
		| LessThanOp 
		| GreaterThanOp
		| LessThanOrEqOp 
		| GreaterThanOrEqOp
		| NotOp 
		| AndOp 
		| OrOp
        
EqOp -> IntegerExpression == IntegerExpression

LessThanOp -> IntegerExpression < IntegerExpression

GreaterThanOp -> IntegerExpression > IntegerExpression

LessThanOrEqOp -> IntegerExpression leq IntegerExpression

GreaterThanOrEqOp -> IntegerExpression geq IntegerExpression

NotOp -> ! IntegerExpression

AndOp -> BooleanExpression and BooleanExpression

OrOp -> BooleanExpression and BooleanExpression
    
ProcedureDeclaration ->  T_r ProcedureName ( T_1 VariableNames_1 , T_2 VariableNames_2 , ... , T_k VariableNames_k ) indent ScopedLevelStatement dedent