SymbolTable -> Declarations

Declarations -> Declaration Declarations
              | EPSILON

Declaration -> Variable
             | Function
             | EPSILON

Variable -> Type identifier

Function -> ReturnType identifier ( Parameter )

ReturnType -> nothing
            | Type

Parameter -> Type identifier
           | CompoundParameter
           | EPSILON

CompoundParameter -> Parameter , Parameter

Type -> IntType
      | RegisterType
      | BooleanType

ParameterTypes -> Type ParameterTypes
                | EPSILON

IntType -> int8
         | int16
         | int32
         | uint8
         | uint16
         | uint32

RegisterType -> register8
              | register16

BooleanType -> bool