SymbolTable -> Declarations

Declarations -> Declaration Declarations
              | EPSILON

Declaration -> Variable
             | Function
             | EPSILON

Variable -> Type identifier
          | Type returnId

Function -> ReturnType identifier ( Parameters )

ReturnType -> nothing
            | Type

Parameters -> Parameter ParametersP
            | EPSILON

ParametersP -> , Parameter ParametersP
             | EPSILON

Parameter -> Type identifier

Type -> IntType
      | RegisterType
      | BooleanType

ParameterTypes -> Type ParameterTypes
                | EPSILON

IntType -> int8
         | int16
         | int32
         | uint8
         | uint16
         | uint32

RegisterType -> register8
              | register16

BooleanType -> bool